# General
name: "Gabriel Aramburu"
description: "Software Architect"
url: http://garamburu.com

markdown: kramdown 
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: gabamnml
twitter: gabamnml
github: gabamnml
google: +gabamnml

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"

gems:
  - jekyll-sitemap
