# Site settings
title: Gabriel Aramburu
email: hello@garamburu.com
description: "This is my attempt at calling the former ''blog''. Here you will find all kinds of great things in my life, browsing code, ideas of life, voyages, whatever. Enjoy!"
baseurl: ""
url: "http://garamburu.com"
username: "gabamnml"
mini-desc: "Programmer"

# Build settings
markdown: kramdown
permalink: pretty
