# General
name: "Gabriel Aramburu"
description: "Fullstack Developer"
url: http://localhost:4000

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: gabamnml
twitter: gabamnml
github: gabamnml
google: +gabamnml

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"